baseURL = ""

defaultContentLanguage = "zh-cn"

languageCode = "zh-CN"
hasCJKLanguage = true
title = "Moon 的博客"

theme = "LoveIt"

[params]
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "notes"
    pre = ""
    post = ""
    name = "文章"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false
